[build]
  command = "pnpm install && pnpm build"
  publish = "docs"

[build.environment]
	NODE_VERSION = "22.15.0"
	MERMAID_ANALYTICS_URL = ''
	MERMAID_DOCS_URL = 'https://mermaid.js.org'
	MERMAID_DOMAIN = ''
	MERMAID_RENDERER_URL = 'https://mermaid.ink'
	MERMAID_KROKI_RENDERER_URL = 'https://kroki.io'
	MERMAID_IS_ENABLED_MERMAID_CHART_LINKS = 'false'

[[redirects]]
  from = "/index.html"
  to = "/diagrams"
  status = 301
  force = true
